[package]
name = "pt-signal"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
parking_lot.workspace = true
reqwest = { version = "0.12", features = ["json", "rustls-tls", "blocking"] }
serde.workspace = true
serde_json.workspace = true
pt-core = { path = "../pt-core" }
tokio.workspace = true
pt-coinbase = { path = "../pt-coinbase" }
tracing.workspace = true
